"""polishing alembic set up

Revision ID: c0c1f71870d2
Revises: b2801bba0f1d
Create Date: 2026-06-04 12:53:48.471873

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'c0c1f71870d2'
down_revision: Union[str, Sequence[str], None] = 'b2801bba0f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
